// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4fvI_x7i6PXR7Ie0-4QLHj4E6CBzBL58',
    appId: '1:473544749748:web:ff9be73f99dec9b4bfdde1',
    messagingSenderId: '473544749748',
    projectId: 'ecofriendly-banking',
    authDomain: 'ecofriendly-banking.firebaseapp.com',
    storageBucket: 'ecofriendly-banking.appspot.com',
    measurementId: 'G-WSEEZ2HHSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdzMbTBdmQ15R4jVbj3IOGMTD5kvih2CE',
    appId: '1:473544749748:android:1bc00731558b4584bfdde1',
    messagingSenderId: '473544749748',
    projectId: 'ecofriendly-banking',
    storageBucket: 'ecofriendly-banking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-_eSOUsmY-PDZSJrUtg_QXlxXw19Sgk',
    appId: '1:473544749748:ios:485ad8efd0ff03e4bfdde1',
    messagingSenderId: '473544749748',
    projectId: 'ecofriendly-banking',
    storageBucket: 'ecofriendly-banking.appspot.com',
    iosBundleId: 'com.example.fintechproject.ecofriendlyBankingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ-_eSOUsmY-PDZSJrUtg_QXlxXw19Sgk',
    appId: '1:473544749748:ios:7510062c4e78cfb5bfdde1',
    messagingSenderId: '473544749748',
    projectId: 'ecofriendly-banking',
    storageBucket: 'ecofriendly-banking.appspot.com',
    iosBundleId: 'com.example.fintechproject.ecofriendlyBankingSystem.RunnerTests',
  );
}
